# Generated by Django 6.0.1 on 2026-01-21 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_es', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('image_name', models.CharField(blank=True, default='default.jpg', help_text="Enter the image filename (eg 'science museum.jpg)", max_length=30)),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
