# Generated by Django 6.0.1 on 2026-01-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_es', '0004_commentreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTextReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=5)),
                ('content', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tourism_es.cardtext')),
            ],
        ),
    ]
