# Generated by Django 6.0.1 on 2026-01-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_es', '0005_cardtextreactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardTextReactions',
            new_name='CardTextTranslation',
        ),
    ]
