# Generated by Django 6.0.1 on 2026-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_es', '0006_rename_cardtextreactions_cardtexttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=7),
        ),
    ]
